// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/v1/aboutRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/aboutRouter').default>>>>
    }
    '/v1/addressesRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/addressesRouter').default>>>>
    }
    '/v1/authRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/authRouter').default>>>>
    }
    '/v1/bannerRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/bannerRouter').default>>>>
    }
    '/v1/categoriesNewsRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/categoriesNewsRouter').default>>>>
    }
    '/v1/categoriesProductRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/categoriesProductRouter').default>>>>
    }
    '/v1/fileManageRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/fileManageRouter').default>>>>
    }
    '/v1': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/index').default>>>>
    }
    '/v1/locationRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/locationRouter').default>>>>
    }
    '/v1/orderManageRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/orderManageRouter').default>>>>
    }
    '/v1/paymentTransactionRoutes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/paymentTransactionRoutes').default>>>>
    }
    '/v1/postsNewsRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/postsNewsRouter').default>>>>
    }
    '/v1/productReviewRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/productReviewRouter').default>>>>
    }
    '/v1/productRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/productRouter').default>>>>
    }
    '/v1/settingRouter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/settingRouter').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}