// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/v1/addresses.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/addresses.router').default>>>>
    }
    '/v1/admin/about.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/about.router').default>>>>
    }
    '/v1/admin/account.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/account.router').default>>>>
    }
    '/v1/admin/banner.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/banner.router').default>>>>
    }
    '/v1/admin/categories-news.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/categories-news.router').default>>>>
    }
    '/v1/admin/categories-product.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/categories-product.router').default>>>>
    }
    '/v1/admin': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/index').default>>>>
    }
    '/v1/admin/itranslation.routes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/itranslation.routes').default>>>>
    }
    '/v1/admin/order-manage.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/order-manage.router').default>>>>
    }
    '/v1/admin/payment-transaction.routes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/payment-transaction.routes').default>>>>
    }
    '/v1/admin/posts-news.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/posts-news.router').default>>>>
    }
    '/v1/admin/product-review.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/product-review.router').default>>>>
    }
    '/v1/admin/product.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/product.router').default>>>>
    }
    '/v1/admin/setting.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/setting.router').default>>>>
    }
    '/v1/admin/users.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/users.router').default>>>>
    }
    '/v1/admin/variant-group.routes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/variant-group.routes').default>>>>
    }
    '/v1/admin/voucher-usage.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/voucher-usage.router').default>>>>
    }
    '/v1/admin/voucher.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/admin/voucher.router').default>>>>
    }
    '/v1/auth.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/auth.router').default>>>>
    }
    '/v1/banner.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/banner.router').default>>>>
    }
    '/v1/categories-news.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/categories-news.router').default>>>>
    }
    '/v1/categories-product.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/categories-product.router').default>>>>
    }
    '/v1': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/index').default>>>>
    }
    '/v1/order-manage.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/order-manage.router').default>>>>
    }
    '/v1/posts-news.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/posts-news.router').default>>>>
    }
    '/v1/product-review.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/product-review.router').default>>>>
    }
    '/v1/product.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/product.router').default>>>>
    }
    '/v1/shared/base-information.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/shared/base-information.router').default>>>>
    }
    '/v1/shared/file-manage.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/shared/file-manage.router').default>>>>
    }
    '/v1/shared': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/shared/index').default>>>>
    }
    '/v1/shared/location.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/shared/location.router').default>>>>
    }
    '/v1/users.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/users.router').default>>>>
    }
    '/v1/variant-group.routes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/variant-group.routes').default>>>>
    }
    '/v1/voucher.router': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/voucher.router').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}