export const FOLDER_UPLOAD = {
  ABOUT: 'About',
  BANNER: 'BANNER',
  IMAGE_BLOCK: 'ImageAds',
  CATEGORY_NEWS: 'CategoryNews',
  CATEGORY_PRODUCT: 'CategoryProduct',
  DEFAULT: 'Default',
  MEMBER: 'Member/member',
  MEMBER_MAIN: 'Member',
  CONFIG: 'Config',
  POST: 'PostsNews',
  PRODUCT: 'Product',
  VOUCHER: 'Voucher',
  FLASH_SALE: 'FlashSale',
}