import type { MenuItem } from '@/server/types/common/menu-item';

export const ROUTES : { ADMIN: Record<string, MenuItem>; PUBLIC: Record<string, MenuItem> } = {
  ADMIN: {
    LOGIN: {
      path: '/admin/login',
      label: 'Đăng nhập',
      icon: 'login',
      middleware: ['admin-role'],
      layout: 'admin-auth-layout',
    },
    ACCOUNT: {
      path: '/admin/account',
      label: 'Tài khoản',
      icon: 'account_circle',
      middleware: [''],
      layout: 'admin-layout',
      roles: ["superadmin", "editor"],
      isShowMenuAccount: true,
    },
    ACCOUNT_LIST: {
      path: '/admin/account/list',
      label: 'QL Tài khoản',
      icon: 'person',
      middleware: [''],
      layout: 'admin-layout',
      isShowMenuAccount: true,
      roles: ["superadmin"],
    },
    ABOUT: {
      path: '/admin/about',
      label: 'Giới Thiệu',
      icon: 'store',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
    },
    PRODUCT: {
      label: 'Sản phẩm',
      icon: 'inventory_2',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
      children: {
        LIST: {
          path: '/admin/product/product',
          label: 'QL Sản phẩm',
          icon: 'list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin", "editor"],
        },
        CATEGORY: {
          path: '/admin/product/category',
          label: 'QL Danh mục SP',
          icon: 'category',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin", "editor"],
        },
        VARIANT_GROUP: {
          path: '/admin/product/variant-group',
          label: 'QL Biến thể',
          icon: 'category',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin", "editor"],
        },
        REVIEW: {
          path: '/admin/product/review',
          label: 'Đánh giá',
          icon: 'comment',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin", "editor"],
        },
      },
    },
    VOUCHER: {
      label: 'Voucher',
      icon: 'sell',
      isShowSidebar: true,
      roles: ["superadmin"],
      children: {
        LIST: {
          path: '/admin/voucher',
          label: 'QL Voucher',
          icon: 'list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin"],
        },
        USAGE: {
          path: '/admin/voucher/usage',
          label: 'Đã sử dụng',
          icon: 'list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin"],
        },
      },
    },
    ORDER: {
      path: '/admin/order',
      label: 'QL Đơn hàng',
      icon: 'assignment',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
    },
    NEWS: {
      label: 'Tin tức',
      icon: 'view_list',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
      children: {
        CATEGORY: {
          path: '/admin/news/category',
          label: 'QL Danh mục Tin',
          icon: 'view_list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin", "editor"],
        },
        POST: {
          path: '/admin/news/post',
          label: 'QL Tin tức',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin", "editor"],
        },
      },
    },
    BANNER: {
      path: '/admin/banner',
      label: 'QL Banner',
      icon: 'image',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
    },
    USER: {
      label: 'Thành viên',
      icon: 'person',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
      children: {
        CUSTOMER: {
          path: '/admin/user',
          label: 'QL Khách hàng',
          icon: 'person',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin"],
        },
        MEMBERSHIP_LEVEL: {
          path: '/admin/user/membership',
          label: 'Hạng thành viên',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin"],
        },
        MEMBERSHIP_BENEFIT: {
          path: '/admin/user/benefit',
          label: 'Lợi ích thành viên',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin", "editor"],
        },
        REWARD_HISTORY: {
          path: '/admin/user/reward-history',
          label: 'Lịch sử tích điểm',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
          roles: ["superadmin"],
        },
      },
    },
    ITRANSLATION: {
      path: '/admin/itranslation',
      label: 'Đa ngôn ngữ',
      icon: 'translate',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
    },
    IMAGE_BLOCK: {
      path: '/admin/image-block',
      label: 'QL Image Ads',
      icon: 'image',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
    },
    FILE_MANAGE: {
      path: '/admin/file-manage',
      label: 'Thư viện ảnh',
      icon: 'image',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
      roles: ["superadmin", "editor"],
    },
    BASE_INFORMATION: {
      path: '/admin/base-information',
      label: 'Cài đặt',
      icon: 'settings',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: false,
      isShowMenuAccount: true,
      roles: ["superadmin", "editor"],
    },
  },
  PUBLIC: {
    HOME: {
      path: '/',
      label: 'Trang chủ',
      icon: 'home',
      middleware: ['auth-login'],
      layout: 'default',
      headerTypeLeft: 'name',
    },
    ORDER: {
      path: '/order',
      label: 'Mới nhất',
      icon: 'mode_heat',
      middleware: ['auth-login'],
      layout: 'default',
      headerTypeLeft: 'address',
    },
    ORDER_TRACKING: {
      path: '/order/tracking',
      label: 'Theo doi don hàng',
      icon: 'inventory_2',
      middleware: ['auth-login'],
      layout: 'default',
      headerTypeLeft: 'logo',
    },
    CLUB: {
      path: '/login',
      label: 'Point club',
      icon: 'star',
      middleware: ['auth-login'],
      layout: 'default',
    },
    LOGIN: {
      path: '/login',
      label: 'Đăng nhập',
      icon: 'login',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    REGISTER: {
      path: '/register',
      label: 'Đăng ký',
      icon: 'app_registration',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    FORGOT_PASSWORD: {
      path: '/forgot-password',
      label: 'Quên mật khẩu',
      icon: 'lock_reset',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    RESET_PASSWORD: {
      path: '/reset-password',
      label: 'Đôi mật khẩu',
      icon: 'lock_reset',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    MENU_ACCOUNT: {
      path: '/account/menu',
      label: 'Tài khoản',
      icon: 'person',
      middleware: ['auth-login'],
      layout: 'user-layout',
      headerTypeLeft: 'logo',
    },
    ACCOUNT: {
      label: 'Tài khoản',
      icon: 'person',
      layout: 'user-layout',
      middleware: ['auth-login'],
      headerTypeLeft: 'logo',
      path: '/account',
      children: {
        INFO: {
          path: '/account/info',
          label: 'Thông tin tài khoản',
          icon: 'person',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        ORDERS: {
          path: '/account/orders',
          label: 'Lịch sử đơn hàng',
          icon: 'prescriptions',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        POINT: {
          path: '/account/point',
          label: 'Lịch sử tích điểm',
          icon: 'description',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        WALLET_VOUCHER: {
          path: '/account/wallet-voucher',
          label: 'Ví Voucher',
          icon: 'confirmation_number',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        USER_ADDRESS: {
          path: '/account/user-address',
          label: 'Sổ địa chỉ',
          icon: 'edit_location',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        REVIEWS: {
          path: '/account/reviews',
          label: 'Đánh giá đơn hàng',
          icon: 'comment',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        WISHLIST: {
          path: '/account/wishlist',
          label: 'Sản phẩm yêu thích',
          icon: 'favorite',
          middleware: ['auth-login'],
          layout: 'user-layout',
        }
      }
    },
    CONTACT: {
      path: '/contact',
      label: 'Liên hệ',
      icon: 'contact_mail',
      middleware: ['auth-login'],
      layout: 'default',
    },
    NEWS: {
      label: 'Tin tức',
      icon: 'article',
      middleware: ['auth-login'],
      children: {
        MAIN: {
          path: '/blog',
          label: 'Tin tức',
          icon: 'article',
          middleware: ['auth-login'],
          layout: 'default-breadcrumb',
        },
        CATEGORY: {
          path: '/blog-category',
          label: 'Danh mục Blog',
          icon: 'description',
          middleware: ['category-news-detail','auth-login'],
          layout: 'default-breadcrumb',
        },
        SEARCH: {
          path: '/blog/search',
          label: 'Kết quả tìm kiếm',
          icon: 'article',
          middleware: ['auth-login'],
          layout: 'default-breadcrumb',
        },
        DETAIL: {
          name: 'post-detail',
          path: '/blog/:slug',
          label: 'Chi tiết Blog',
          icon: 'description',
          middleware: ['post-detail','auth-login'],
          layout: 'default-breadcrumb',
        },
      }
    },
    PRODUCT: {
      label: 'Sản phẩm',
      icon: 'shopping_cart',
      headerTypeLeft: 'logo',
      children: {
        SALE: {
          path: '/product/giam-gia',
          label: 'Khuyến mãi',
          icon: 'percent_discount',
          middleware: ['auth-login'],
          layout: 'default',
          headerTypeLeft: 'address',
        },
        MOST_ORDER: {
          path: '/product/ban-chay',
          label: 'Bán chạy',
          icon: 'shopping_cart',
          middleware: ['auth-login'],
          layout: 'default',
          headerTypeLeft: 'address',
        },
        LIST: {
          path: '/products',
          label: 'Danh sách sản phẩm',
          icon: 'list',
          middleware: ['auth-login'],
          layout: 'default',
        },
        CATEGORY: {
          path: '/product-category',
          label: 'Danh mục sản phẩm',
          icon: 'description',
          middleware: ['category-product-detail','auth-login'],
          layout: 'default',
          headerTypeLeft: 'address',
        },
        SEARCH: {
          path: '/product/search',
          label: 'Kết quả tìm kiếm',
          icon: 'article',
          middleware: ['product-search-result','auth-login'],
          layout: 'default',
        },
        DETAIL: {
          path: '/product/:slug',
          label: 'Chi tiết sản phẩm',
          icon: 'info',
          middleware: ['auth-login','product-detail'],
          layout: 'default',
          headerTypeLeft: 'logo',
        },
      },
    },
    CART: {
      path: '/cart',
      label: 'Đặt hàng',
      icon: 'info',
      middleware: ['auth-login'],
      layout: 'cart-layout',
      headerTypeLeft: 'logo',
    },
    PAYMENT: {
      path: '/payment',
      label: 'Thanh toán đơn hàng',
      icon: 'info',
      middleware: ['auth-login'],
      layout: 'default',
      headerTypeLeft: 'logo',
    },
    ABOUT: {
      path: '/',
      label: 'Giới thiệu',
      icon: 'info',
      middleware: ['auth-login'],
      layout: 'default',
    },
    PAGE: {
      label: 'Custom page',
      icon: 'info',
      headerTypeLeft: 'logo',
      layout: 'default-breadcrumb',
      children: {
        POINT_CLUB: {
          path: '/page/point-club',
          label: 'Point Club',
          icon: 'info',
          middleware: ['auth-login'],
          layout: 'default-breadcrumb',
          headerTypeLeft: 'logo',
        },
      },
    },
    ERROR: {
      path: '/404',
      label: 'Không tìm thấy trang',
      icon: 'info',
      middleware: ['auth-login'],
      layout: 'default',
    },
  },
};