import type { MenuItem } from '@/server/types/common/menu-item';

export const ROUTES : { ADMIN: Record<string, MenuItem>; PUBLIC: Record<string, MenuItem> } = {
  ADMIN: {
    LOGIN: {
      path: '/admin/login',
      label: 'Đăng nhập',
      icon: 'login',
      middleware: [''],
      layout: 'admin-auth-layout',
      isShowSidebar: false,
    },
    ACCOUNT: {
      path: '/admin/account',
      label: 'Tài khoản',
      icon: 'inventory_2',
      middleware: [''],
      layout: 'admin-layout',
      isShowSidebar: false,
      isShowMenuAccount: true,
    },
    ABOUT: {
      path: '/admin/about',
      label: 'Giới Thiệu',
      icon: 'store',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
    },
    PRODUCT: {
      label: 'Sản phẩm',
      icon: 'inventory_2',
      isShowSidebar: true,
      children: {
        LIST: {
          path: '/admin/product/product',
          label: 'QL Sản phẩm',
          icon: 'list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
        CATEGORY: {
          path: '/admin/product/category',
          label: 'QL Danh mục SP',
          icon: 'category',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
        REVIEW: {
          path: '/admin/product/review',
          label: 'Đánh giá',
          icon: 'comment',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
      },
    },
    VOUCHER: {
      label: 'Voucher',
      icon: 'inventory_2',
      isShowSidebar: true,
      children: {
        LIST: {
          path: '/admin/voucher',
          label: 'QL Voucher',
          icon: 'list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
        USAGE: {
          path: '/admin/voucher/usage',
          label: 'Đã sử dụng',
          icon: 'list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
      },
    },
    ORDER: {
      path: '/admin/order',
      label: 'QL Đơn hàng',
      icon: 'assignment',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
    },
    NEWS: {
      label: 'Tin tức',
      icon: 'view_list',
      isShowSidebar: true,
      children: {
        CATEGORY: {
          path: '/admin/news/category',
          label: 'QL Danh mục Tin',
          icon: 'view_list',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
        POST: {
          path: '/admin/news/post',
          label: 'QL Tin tức',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
      },
    },
    BANNER: {
      path: '/admin/banner',
      label: 'QL Banner',
      icon: 'image',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
    },
    USER: {
      label: 'Thanh vien',
      icon: 'person',
      isShowSidebar: true,
      children: {
        CUSTOMER: {
          path: '/admin/user',
          label: 'QL Khách hàng',
          icon: 'person',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
        MEMBERSHIP_LEVEL: {
          path: '/admin/user/membership',
          label: 'Loai thanh vien',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
        MEMBERSHIP_BENEFIT: {
          path: '/admin/user/benefit',
          label: 'Loi ich thanh vien',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
        REWARD_HISTORY: {
          path: '/admin/user/reward-history',
          label: 'Lich su tich diem',
          icon: 'article',
          middleware: ['admin-role'],
          layout: 'admin-layout',
          isShowSidebar: true,
        },
      },
    },
    FILE_MANAGE: {
      path: '/admin/file-manage',
      label: 'Thư viện ảnh',
      icon: 'image',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: true,
    },
    BASE_INFORMATION: {
      path: '/admin/base-information',
      label: 'Cài đặt',
      icon: 'settings',
      middleware: ['admin-role'],
      layout: 'admin-layout',
      isShowSidebar: false,
      isShowMenuAccount: true,
    },
  },
  PUBLIC: {
    HOME: {
      path: '/',
      label: 'Trang chủ',
      icon: 'home',
      middleware: [],
      layout: 'default',
      headerTypeLeft: 'name',
    },
    ORDER: {
      path: '/order',
      label: 'Đặt hàng',
      icon: 'inventory_2',
      middleware: ['auth-user'],
      layout: 'default',
      headerTypeLeft: 'address',
    },
    ORDER_TRACKING: {
      path: '/order-tracking',
      label: 'Theo doi don hàng',
      icon: 'inventory_2',
      middleware: [],
      layout: 'default',
      headerTypeLeft: 'logo',
    },
    ORDER_HISTORY: {
      path: '/order-history',
      label: 'Lịch sử đơn hàng',
      icon: 'history',
      middleware: ['auth-user'],
      layout: 'default',
      headerTypeLeft: 'logo',
    },
    LOGIN: {
      path: '/login',
      label: 'Đăng nhập',
      icon: 'login',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    REGISTER: {
      path: '/register',
      label: 'Đăng ký',
      icon: 'app_registration',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    FORGOT_PASSWORD: {
      path: '/forgot-password',
      label: 'Quên mật khẩu',
      icon: 'lock_reset',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    RESET_PASSWORD: {
      path: '/reset-password',
      label: 'Đôi mật khẩu',
      icon: 'lock_reset',
      middleware: ['auth-login'],
      layout: 'auth-layout',
    },
    MENU_ACCOUNT: {
      path: '/account/menu',
      label: 'Tài khoản',
      icon: 'person',
      middleware: ['auth-login'],
      // layout: 'user-layout',
      headerTypeLeft: 'logo',
    },
    ACCOUNT: {
      label: 'Tài khoản',
      icon: 'person',
      layout: 'user-layout',
      middleware: ['auth-login'],
      headerTypeLeft: 'logo',
      children: {
        INFO: {
          path: '/account/info',
          label: 'Thông tin tài khoản',
          icon: 'person',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        ORDERS: {
          path: '/account/orders',
          label: 'Lịch sử đơn hàng',
          icon: 'prescriptions',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        POINT: {
          path: '/account/point',
          label: 'Lịch sử Point',
          icon: 'description',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        WALLET_VOUCHER: {
          path: '/account/wallet-voucher',
          label: 'Ví Voucher',
          icon: 'confirmation_number',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        USER_ADDRESS: {
          path: '/account/user-address',
          label: 'Sổ địa chỉ',
          icon: 'edit_location',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        REVIEWS: {
          path: '/account/reviews',
          label: 'Đánh giá và phản hồi',
          icon: 'comment',
          middleware: ['auth-login'],
          layout: 'user-layout',
        },
        WISHLIST: {
          path: '/account/wishlist',
          label: 'San pham yeu thich',
          icon: 'favorite',
          middleware: ['auth-login'],
          layout: 'user-layout',
        }
      }
    },
    CONTACT: {
      path: '/contact',
      label: 'Liên hệ',
      icon: 'contact_mail',
      middleware: [],
      layout: 'default',
    },
    NEWS: {
      label: 'Tin tức',
      icon: 'article',
      children: {
        MAIN: {
          path: '/news',
          label: 'Uu dai',
          icon: 'article',
          middleware: ['news-main'],
          layout: 'default',
        },
        CATEGORY: {
          path: '/news-category',
          label: 'Danh mục Blog',
          icon: 'description',
          middleware: ['category-news-detail'],
          layout: 'default',
        },
        DETAIL: {
          name: 'post-detail',
          path: '/post',
          label: 'Chi tiết Blog',
          icon: 'description',
          middleware: ['post-detail'],
          layout: 'default',
        }
      }
    },
    PRODUCT: {
      label: 'Sản phẩm',
      icon: 'shopping_cart',
      children: {
        LIST: {
          path: '/products',
          label: 'Danh sách sản phẩm',
          icon: 'list',
          middleware: [],
          layout: 'default',
        },
        CATEGORY: {
          path: '/product-category',
          label: 'Danh mục sản phẩm',
          icon: 'description',
          middleware: ['category-product-detail'],
          layout: 'default',
        },
        DETAIL: {
          path: '/product',
          label: 'Chi tiết sản phẩm',
          icon: 'info',
          middleware: ['product-detail'],
          layout: 'default',
        },
      },
    },
    CART: {
      path: '/cart',
      label: 'Dat hang',
      icon: 'info',
      middleware: [],
      layout: 'default',
      headerTypeLeft: 'logo',
    },
    PAYMENT: {
      path: '/payment',
      label: 'Thanh toan don hang',
      icon: 'info',
      middleware: [],
      layout: 'default',
      headerTypeLeft: 'logo',
    },
    ABOUT: {
      path: '/about',
      label: 'Giới thiệu',
      icon: 'info',
      middleware: [],
      layout: 'default',
    },
    ERROR: {
      path: '/404',
      label: 'Không tìm thấy trang',
      icon: 'info',
      middleware: [],
      layout: 'default',
    },
  },
};