export const API_ENDPOINTS_ADMIN = {
  SETTINGS: {
    UPDATE: '/settings/update',
  },
  ACCOUNT: {
    VERIFY_TOKEN: '/account/verify-token',
    LOGIN: '/account/login',
    RESET_PASSWORD: '/account/reset-password',
    GET_ME: (id: string) => `/account/me/${id}`,
    UPDATE: '/account/update',
    CHANGE_PASSWORD: '/account/change-password',
    LOGOUT: '/account/logout',
    ACCOUNT_LIST: "/account/list",
    DELETE: (id: string) => `/account/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/account/toggleActive/${id}`,
    CREATE: '/account/create',
  },
  ABOUT: {
    LIST: '/about',
    GET_BY_ID: (id: string) => `/about/${id}`,
    CREATE: '/about',
    UPDATE: (id: string) => `/about/${id}`,
    DELETE: (id: string) => `/about/${id}`,
    UPDATE_ORDER: (id: string) => `/about/updateOrder/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/about/toggleActive/${id}`,
  },
  CATEGORIES: {
    LIST: '/categories',
    LIST_TREE: '/categories/tree',
    GET_BY_ID: (id: string) => `/categories/${id}`,
    GET_CHILDREN: (id: string) => `/categories/${id}/children`,
    CREATE: '/categories',
    UPDATE: (id: string) => `/categories/${id}`,
    DELETE: (id: string) => `/categories/${id}`,
    UPDATE_ORDER: (id: string) => `/categories/updateOrder/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/categories/toggleActive/${id}`,
  },
  PRODUCTS: {
    LIST_ALL: '/products',
    GET_BY_ID: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
    UPDATE: (id: string) => `/products/${id}`,
    CREATE: '/products',
    TOGGLE_ACTIVE: (id: string) => `/products/toggleActive/${id}`,
  },
  VARIANT_GROUPS: {
    LIST_ALL: '/variant-groups',
    LIST_ACTIVE: '/variant-groups/active',
    DETAIL: '/variant-groups/:id',
    CREATE: '/variant-groups',
    UPDATE: '/variant-groups/:id',
    DELETE: '/variant-groups/:id',
    TOGGLE_ACTIVE: '/variant-groups/:id/toggle-active',
    BY_TYPE: '/variant-groups/type/:type',
  },
  ORDERS: {
    LIST: '/orders',
    GET_BY_ID: (id: string) => `/orders/${id}`,
    DELETE: (id: string) => `/orders/${id}`,
    LIST_STATUS: '/orders/status',
    UPDATE_STATUS: '/orders/status',
    LIST_PAYMENTS: '/orders/payments',
    CHECK_POINT: "/orders/check-point",
  },
  CATEGORIES_NEWS: {
    LIST: '/categoriesNews',
    GET_BY_ID: (id: string) => `/categoriesNews/${id}`,
    CREATE: '/categoriesNews',
    UPDATE: (id: string) => `/categoriesNews/${id}`,
    DELETE: (id: string) => `/categoriesNews/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/categoriesNews/toggleActive/${id}`,
    UPDATE_ORDER: (id: string) => `/categoriesNews/updateOrder/${id}`,
  },
  NEWS_POSTS: {
    LIST: '/newsPosts',
    GET_BY_ID: (id: string) => `/newsPosts/${id}`,
    CREATE: '/newsPosts',
    UPDATE: (id: string) => `/newsPosts/${id}`,
    DELETE: (id: string) => `/newsPosts/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/newsPosts/toggleActive/${id}`,
  },
  BANNERS: {
    LIST: '/banners',
    GET_BY_ID: (id: string) => `/banners/${id}`,
    CREATE: '/banners',
    UPDATE: (id: string) => `/banners/${id}`,
    DELETE: (id: string) => `/banners/${id}`,
    UPDATE_ORDER: (id: string) => `/banners/updateOrder/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/banners/toggleActive/${id}`,
  },
  USERS: {
    DELETE: (id: string) => `/users/${id}`,
    GET_BY_ID: (id: string) => `/users/${id}`,
    LIST: '/users',
    LIST_MEMBERSHIP_LEVEL: '/users/membership-level',
    GET_MEMBERSHIP_LEVEL_BY_ID: (id: string) => `/users/membership-level/${id}`,
    UPDATE_MEMBERSHIP_LEVEL: (id: string) => `/users/membership-level/${id}`,
    SET_POINT: '/users/set-point',
    TOGGLE_ACTIVE: (id: string) => `/users/toggleActive/${id}`,
    CREATE_MEMBERSHIP_BENEFIT: '/users/membership-benefit',
    LIST_MEMBERSHIP_BENEFIT: '/users/membership-benefit',
    GET_MEMBERSHIP_BENEFIT_BY_ID: (id: string) => `/users/membership-benefit/${id}`,
    UPDATE_MEMBERSHIP_BENEFIT: (id: string) => `/users/membership-benefit/${id}`,
    DELETE_MEMBERSHIP_BENEFIT: (id: string) => `/users/membership-benefit/${id}`,
    REWARD_HISTORY: '/users/reward-history',
  },
  PAYMENT_TRANSACTIONS: {
    CREATE: '/payment-transactions',
    LIST: '/payment-transactions',
    GET_BY_ID: (id: string) => `/payment-transactions/${id}`,
    DELETE: (id: string) => `/payment-transactions/${id}`,
    UPDATE_STATUS: '/payment-transactions/status',
  },
  PRODUCT_REVIEWS: {
    LIST: '/product-reviews',
    GET_BY_ID: (id: string) => `/product-reviews/${id}`,
    DELETE: (id: string) => `/product-reviews/${id}`,
    UPDATE_STATUS: '/product-reviews/status',
  },
  VOUCHERS: {
    LIST: "/voucher",
    GET_BY_ID: (id: string) => `/voucher/${id}`,
    CREATE: "/voucher",
    UPDATE: (id: string) => `/voucher/${id}`,
    DELETE: (id: string) => `/voucher/${id}`,
    TOGGLE_ACTIVE: (id: string) => `/voucher/${id}/toggle-active`,
  },
  VOUCHERS_USAGE: {
    LIST: "/voucher-usage",
  },
}