export const API_ENDPOINTS = {
  IMAGE_BLOCKS: {
    GET_BY_PAGE: '/image-blocks/by-page',
  },
  ABOUT: {
    LIST: '/about',
    GET_BY_ID: (id: string) => `/about/${id}`,
  },
  CATEGORIES: {
    LIST: '/categories',
    LIST_TREE: '/categories/tree',
    GET_BY_ID: (id: string) => `/categories/${id}`,
    GET_BY_SLUG: (slug: string) => `/categories/slug/${slug}`,
    GET_CHILDREN: (id: string) => `/categories/${id}/children`,
  },
  PRODUCTS: {
    GET_BY_ID: (id: string) => `/products/${id}`,
    RELATED_BY_SLUG: (slug: string) => `/products/related/${slug}`,
    LIST_MOST_ORDER: '/products/most-order',
    LIST_PROMOTION: '/products/promotion',
    LIST_BY_IDS: '/products/by-ids',
    SEARCH: '/products/search',
    LIST_BY_CATEGORY: (categoryId: string) => `/products/category/${categoryId}`,
    LIST_BY_USER_WISHLIST: (id: string) => `/users/${id}/wishlist`,
    ADD_WISHLIST: (userId: string) => `/users/${userId}/wishlist`,
    DELETE_WISHLIST: (userId: string, productId: string) =>
      `/users/${userId}/wishlist/${productId}`,
    CART_DETAIL: '/products/cart-detail',
    CHECK_STOCK: '/products/check-stock'
  },
  VARIANT_GROUPS: {
    LIST_ALL: '/variant-groups',
  },
  ORDERS: {
    LIST_STATUS: '/orders/status',
    LIST_PAYMENTS: '/orders/payment-method',
    CREATE: '/orders',
    LIST: '/orders',
    GET_BY_ID: (id: string) => `/orders/${id}`,
    LIST_BY_USER: (id: string) => `/orders/users/${id}/orders`,
    LIST_REWARDS_BY_USER: (id: string) => `/orders/users/${id}/rewards`,
    CHECK_POINT: "/orders/check-point",
    SHIPPING_FEE: "/orders/shipping/fee",
    CANCEL_REQUEST: "/orders/users/cancel-request",
    PENDING_REWARD: (userId: string) => `/orders/rewards/pending/${userId}`,
    COUNT_BY_STATUS: '/orders/count-by-status',
    PAYMENT_VNPAY: '/orders/payment/vnpay/create',
  },
  CATEGORIES_NEWS: {
    LIST: '/categoriesNews',
    GET_BY_ID: (id: string) => `/categoriesNews/${id}`,
    GET_BY_SLUG: (slug: string) => `/categoriesNews/slug/${slug}`,
  },
  NEWS_POSTS: {
    LIST_PAGINATION: '/newsPosts/pagination',
    LATEST: (limit: number) => `/newsPosts/latest?limit=${limit}`,
    GET_BY_ID: (id: string) => `/newsPosts/${id}`,
    GET_BY_SLUG: (slug: string) => `/newsPosts/slug/${slug}`,
    RELATED_BY_SLUG: (slug: string) => `/newsPosts/related/${slug}`,
    UPDATE_VIEWS: (slug: string) => `/newsPosts/view/${slug}`,
    GET_BY_CATEGORY: (categoryId: string) => `/newsPosts/category/${categoryId}`,
  },
  BANNERS: {
    LIST: '/banners',
  },
  AUTH: {
    VERIFY_TOKEN: '/auth/verify-token',
    REFRESH_TOKEN: '/auth/refresh-token',
    LOGIN: '/auth/login',
    GOOGLE_LOGIN: "/auth/google-login",
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    GET_BY_ID: (id: string) => `/auth/users/${id}`,
    UPDATE: '/auth/users/me',
    LOGOUT: '/auth/logout',
  },
  USERS: {
    SET_POINT: '/auth/set-point',
    LOG_SEARCH_KEYWORD: '/users/search-keywords/log',
    LIST_SEARCH_KEYWORD: (limit: number) => `/users/search-keywords/list?limit=${limit}`,
    LIST_MEMBERSHIP_LEVEL: '/users/membership-level',
    GET_MEMBERSHIP_LEVEL_BY_ID: (id: string) => `/users/membership-level/${id}`,
  },
  ADDRESSES: {
    LIST: '/addresses',
    GET_BY_ID: (id: string) => `/addresses/${id}`,
    CREATE: '/addresses',
    UPDATE: (id: string) => `/addresses/${id}`,
    DELETE: (id: string) => `/addresses/${id}`,
    SET_DEFAULT: (id: string) => `/addresses/${id}/set-default`,
    GET_BY_ID_DEFAULT: '/addresses/default',
  },
  PRODUCT_REVIEWS: {
    LIST: '/product-reviews',
    GET_BY_ID: (id: string) => `/product-reviews/${id}`,
    DELETE: (id: string) => `/product-reviews/${id}`,
    UPDATE_STATUS: '/product-reviews/status',
    SUBMIT: '/product-reviews/submit',
    GET_BY_USER_PENDING: (userId: string) => `/product-reviews/user/${userId}`,
    GET_BY_PRODUCT_ID: (id: string) => `/product-reviews/product/${id}/reviews`,
  },
  VOUCHERS: {
    AVAILABLE: '/voucher',
    ALL: '/voucher/all',
    APPLY: "/voucher/apply",
  },
  FILE_MANAGE: {
    UPLOAD: '/fileManage/images/upload',
    GET_IMAGES: (folder: string) => `/fileManage/images?folder=${folder}`,
    DELETE_IMAGE: (id: string) => `/fileManage/images/delete?publicId=${id}`,
    SEARCH_IMAGE: () => `/fileManage/images/search`
  },
  BASE_INFORMATION: {
    GET: '/base-information',
  },
  PAYMENT_TRANSACTIONS: {
    GET_BY_ID: (id: string) => `/payment-transactions/${id}`,
  },
}