export const API_ENDPOINTS = {
  SETTINGS: {
    UPDATE: '/settings/update',
  },
  ABOUT: {
    LIST: '/about',
    GET_BY_ID: (id) => `/about/${id}`,
    CREATE: '/about',
    UPDATE: (id) => `/about/${id}`,
    DELETE: (id) => `/about/${id}`,
    UPDATE_ORDER: (id) => `/about/updateOrder/${id}`,
    TOGGLE_ACTIVE: (id) => `/about/toggleActive/${id}`,
  },
  CATEGORIES: {
    LIST: '/categories',
    GET_BY_ID: (id) => `/categories/${id}`,
    GET_BY_SLUG: (slug) => `/categories/slug/${slug}`,
    CREATE: '/categories',
    UPDATE: (id) => `/categories/${id}`,
    DELETE: (id) => `/categories/${id}`,
    UPDATE_ORDER: (id) => `/categories/updateOrder/${id}`,
    TOGGLE_ACTIVE: (id) => `/categories/toggleActive/${id}`,
  },
  PRODUCTS: {
    LIST_ALL: '/products',
    GET_BY_ID: (id) => `/products/${id}`,
    DELETE: (id) => `/products/${id}`,
    UPDATE: (id) => `/products/${id}`,
    CREATE: '/products',
    RELATED_BY_SLUG: (slug) => `/products/related/${slug}`,
    TOGGLE_ACTIVE: (id) => `/products/toggleActive/${id}`,
    LIST_MOST_ORDER: (limit) => `/products/most-order?limit=${limit}`,
    LIST_PROMOTION: (limit) => `/products/promotion?limit=${limit}`,
    SEARCH: '/products/search',
    LIST_BY_CATEGORY: (categoryId) => `/categories/${categoryId}/products`,
    LIST_BY_USER_WISHLIST: (id) => `/users/${id}/wishlist`,
    ADD_WISHLIST:  (userId) => `/users/${userId}/wishlist`,
    DELETE_WISHLIST: (userId, productId) =>
      `/users/${userId}/wishlist/${productId}`,
  },
  ORDERS: {
    CREATE: '/orders',
    LIST: '/orders',
    GET_BY_ID: (id) => `/orders/${id}`,
    DELETE: (id) => `/orders/${id}`,
    LIST_STATUS: '/orders/status',
    UPDATE_STATUS: '/orders/status',
    LIST_PAYMENTS: '/orders/payments',
    LIST_BY_USER: (id) => `/orders/users/${id}/orders`,
    LIST_REWARDS_BY_USER: (id) => `/orders/users/${id}/rewards`,
  },
  CATEGORIES_NEWS: {
    LIST: '/categoriesNews',
    GET_BY_ID: (id) => `/categoriesNews/${id}`,
    GET_BY_SLUG: (slug) => `/categoriesNews/slug/${slug}`,
    CREATE: '/categoriesNews',
    UPDATE: (id) => `/categoriesNews/${id}`,
    DELETE: (id) => `/categoriesNews/${id}`,
    TOGGLE_ACTIVE: (id) => `/categoriesNews/toggleActive/${id}`,
    UPDATE_ORDER: (id) => `/categoriesNews/updateOrder/${id}`,
  },
  NEWS_POSTS: {
    LIST: '/newsPosts',
    LIST_PAGINATION: '/newsPosts/pagination',
    LATEST: (limit) => `/newsPosts/latest?limit=${limit}`,
    GET_BY_ID: (id) => `/newsPosts/${id}`,
    GET_BY_SLUG: (slug) => `/newsPosts/slug/${slug}`,
    RELATED_BY_SLUG: (slug) => `/newsPosts/related/${slug}`,
    UPDATE_VIEWS: (slug) => `/newsPosts/view/${slug}`,
    CREATE: '/newsPosts',
    UPDATE: (id) => `/newsPosts/${id}`,
    DELETE: (id) => `/newsPosts/${id}`,
    TOGGLE_ACTIVE: (id) => `/newsPosts/toggleActive/${id}`,
    GET_BY_CATEGORY: (categoryId) => `/newsPosts/category/${categoryId}`,
  },
  BANNERS: {
    LIST: '/banners',
    GET_BY_ID: (id) => `/banners/${id}`,
    CREATE: '/banners',
    UPDATE: (id) => `/banners/${id}`,
    DELETE: (id) => `/banners/${id}`,
    UPDATE_ORDER: (id) => `/banners/updateOrder/${id}`,
    TOGGLE_ACTIVE: (id) => `/banners/toggleActive/${id}`,
  },
  USERS: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    DELETE: (id) => `/auth/${id}`,
    GET_BY_ID: (id) => `/auth/users/${id}`,
    UPDATE: '/auth/users/me',
    LIST: '/auth/users',
    LIST_MEMBERSHIP_LEVEL: '/auth/membership-level',
    GET_MEMBERSHIP_LEVEL_BY_ID: (id) => `/auth/membership-level/${id}`,
    UPDATE_MEMBERSHIP_LEVEL: (id) => `/auth/membership-level/${id}`,
    SET_POINT: '/auth/set-point',
    LOG_SEARCH_KEYWORD: '/auth/search-keywords/log',
    LIST_SEARCH_KEYWORD: (limit) => `/auth/search-keywords/list?limit=${limit}`,
    TOGGLE_ACTIVE: (id) => `/auth/users/toggleActive/${id}`,
    //benefit
    CREATE_MEMBERSHIP_BENEFIT: '/auth/membership-benefit',
    LIST_MEMBERSHIP_BENEFIT: '/auth/membership-benefit',
    GET_MEMBERSHIP_BENEFIT_BY_ID: (id) => `/auth/membership-benefit/${id}`,
    UPDATE_MEMBERSHIP_BENEFIT: (id) => `/auth/membership-benefit/${id}`,
    DELETE_MEMBERSHIP_BENEFIT: (id) => `/auth/membership-benefit/${id}`,
  },
  ADDRESSES: {
    LIST: '/addresses',
    GET_BY_ID: (id) => `/addresses/${id}`,
    CREATE: '/addresses',
    UPDATE: (id) => `/addresses/${id}`,
    DELETE: (id) => `/addresses/${id}`,
    SET_DEFAULT: (id) => `/addresses/${id}/set-default`,
    GET_BY_ID_DEFAULT: (userId) => `/addresses/default/${userId}`,
  },
  FILE_MANAGE: {
    UPLOAD: '/fileManage/images/upload',
    GET_IMAGES: (folder, limit) => `/fileManage/images?folder=${folder}&max_results=${limit}`,
    GET_FOLDERS: () => `/fileManage/images/folders`,
    DELETE_IMAGE: (id) => `/fileManage/images/delete?publicId=${id}`,
    SEARCH_IMAGE: () => `/fileManage/images/search`
  },
  PAYMENT_TRANSACTIONS: {
    CREATE: '/payment-transactions',
    LIST: '/payment-transactions',
    GET_BY_ID: (id) => `/payment-transactions/${id}`,
    DELETE: (id) => `/payment-transactions/${id}`,
    UPDATE_STATUS: '/payment-transactions/status',
  },
  PRODUCT_REVIEWS: {
    LIST: '/product-reviews',
    GET_BY_ID: (id) => `/product-reviews/${id}`,
    DELETE: (id) => `/product-reviews/${id}`,
    UPDATE_STATUS: '/product-reviews/status',
    SUBMIT: '/product-reviews/submit',
    GET_BY_USER_PENDING: (userId) => `/product-reviews/user/${userId}/reviews`,
    GET_BY_PRODUCT_ID: (id) => `/product-reviews/product/${id}/reviews`,
  },
}